import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./resale_bot.db")

# Hard safety defaults
AUTO_BUY = False
AUTO_PUBLISH = False
AUTO_REFUND = False
AUTO_ACCEPT_RETURNS = False
AUTO_SEND_MONEY = False
AUTO_CLOSE_CASES = False
REQUIRE_HUMAN_APPROVAL = True

AUTO_REPLY_FIRST_MESSAGE = True
AUTO_FOLLOW_UP = True
MAX_AUTO_FOLLOWUPS_PER_THREAD = 2
STOP_FOLLOWUPS_IF_CUSTOMER_REPLIES = True
NO_FOLLOWUP_AFTER_REFUND_OR_DISPUTE = True
REQUIRE_APPROVAL_FOR_ANGRY_CUSTOMERS = True

ARCHIVE_ALL_MESSAGES = True
ARCHIVE_AI_REPLIES = True
ARCHIVE_HUMAN_REPLIES = True
ALLOW_DELETE_ARCHIVE = False
ALLOW_EXPORT_ARCHIVE = True
MASK_PAYMENT_INFO = True
MASK_PERSONAL_DATA_IN_EXPORTS = True

AUTO_POST_OWN_CHANNELS = True
AUTO_OPTIMIZE_LISTINGS = True
AUTO_POST_EXTERNAL_COMMUNITIES = False
REQUIRE_APPROVAL_FOR_PAID_ADS = True
REQUIRE_APPROVAL_FOR_OUTREACH = True
